<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>{{ $report['title'] }}</title>

<style>
*{
    box-sizing:border-box;
}

body{
    margin:0;
    font-family:notosans,notosansbengali,sans-serif;
    font-size:9px;
    color:#000;
    background:#fff;
}

.header{
    width:100%;
    text-align:center;
    padding-bottom:8px;
    margin-bottom:10px;
    border-bottom:1px solid #000;
}

.logo{
    height:48px;
    max-width:120px;
    margin-bottom:4px;
}

.organization{
    font-family:notosans,notosansbengali,sans-serif;
    font-size:17px;
    font-weight:bold;
    color:#000;
}

.report-title{
    margin-top:1px;
    font-size:12px;
    font-weight:bold;
    color:#000;
}

.period{
    font-size:9px;
    color:#000;
}

.meta-table{
    width:100%;
    border-collapse:collapse;
    margin-bottom:7px;
}

.meta-table td{
    padding:2px 0;
    border:none;
    font-size:8px;
    color:#000;
}

.report-table{
    width:100%;
    border-collapse:collapse;
    border-spacing:0;
    border:1px solid #000;
}

.report-table th,
.report-table td{
    padding:5px;
    border:0;
    border-right:1px solid #000;
    border-bottom:1px solid #000;
    vertical-align:top;
    color:#000;
    background:#fff;
}

.report-table th:last-child,
.report-table td:last-child{
    border-right:0;
}

.report-table tbody tr:last-child td{
    border-bottom:0;
}

.report-table th{
    font-family:notosans,notosansbengali,sans-serif;
    font-weight:bold;
    text-align:left;
    background:#fff;
}

.report-table td{
    font-family:notosans,notosansbengali,sans-serif;
    word-wrap:break-word;
}

.empty{
    padding:18px!important;
    text-align:center;
    color:#000;
}

.pdf-footer{
    width:100%;
    padding-top:5px;
    border-top:1px solid #000;
    font-family:notosans,notosansbengali,sans-serif;
    font-size:7px;
    color:#000;
    text-align:center;
}
</style>
</head>

<body>

{{-- Fixed footer for every PDF page --}}
<htmlpagefooter name="reportFooter">
    <div class="pdf-footer">
        {{ $organization['name'] }} • Generated by Association Management System
    </div>
</htmlpagefooter>

<sethtmlpagefooter name="reportFooter" value="on" />

<div class="header">

    @if(!empty($organization['logo_path']))
        <img
            src="{{ $organization['logo_path'] }}"
            class="logo"
        >
    @endif

    <div class="organization">
        {{ $organization['name'] }}
    </div>

    <div class="report-title">
        {{ $report['title'] }}
    </div>

    <div class="period">
        @if($from || $to)
            Report Period:
            {{ $from ?: 'Beginning' }}
            -
            {{ $to ?: 'Present' }}
        @else
            All-time Report
        @endif
    </div>

</div>

<table class="meta-table">
    <tr>
        <td>
            Generated: {{ now()->format('d M Y h:i A') }}
        </td>

        <td style="text-align:right">
            Total Records: {{ count($report['rows']) }}
        </td>
    </tr>
</table>

<table class="report-table">

    <thead>
        <tr>
            @foreach($report['headings'] as $heading)
                <th>{{ $heading }}</th>
            @endforeach
        </tr>
    </thead>

    <tbody>

        @forelse($report['rows'] as $row)

            <tr>
                @foreach($row as $value)
                    <td>{{ $value }}</td>
                @endforeach
            </tr>

        @empty

            <tr>
                <td
                    colspan="{{ count($report['headings']) }}"
                    class="empty"
                >
                    No data available.
                </td>
            </tr>

        @endforelse

    </tbody>

</table>

</body>
</html>